test_anagram (__main__.TestExercice) ... ERROR
test_doubles (__main__.TestExercice) ... ok
test_grades (__main__.TestExercice) ... ERROR
test_histogram (__main__.TestExercice) ... FAIL
test_order (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_anagram (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 35, in test_anagram
    output = [exercice.anagrams(v) for v in words]
  File "test_exercice.py", line 35, in <listcomp>
    output = [exercice.anagrams(v) for v in words]
  File "/home/runner/work/c03_ch6_exercices-Eli-michaud/c03_ch6_exercices-Eli-michaud/exercice.py", line 18, in anagrams
    if len(mot1) == len(mot2):
UnboundLocalError: local variable 'mot1' referenced before assignment

======================================================================
ERROR: test_grades (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 63, in test_grades
    output = [exercice.best_grades(v) for v in values]
  File "test_exercice.py", line 63, in <listcomp>
    output = [exercice.best_grades(v) for v in values]
  File "/home/runner/work/c03_ch6_exercices-Eli-michaud/c03_ch6_exercices-Eli-michaud/exercice.py", line 47, in best_grades
    if moyenne[Ã©tudiant] == moyenneLaPlusHaute:
TypeError: 'float' object is not subscriptable

======================================================================
ERROR: test_order (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 19, in test_order
    output = [exercice.order(v) for v in values]
  File "test_exercice.py", line 19, in <listcomp>
    output = [exercice.order(v) for v in values]
  File "/home/runner/work/c03_ch6_exercices-Eli-michaud/c03_ch6_exercices-Eli-michaud/exercice.py", line 10, in order
    return list == sorted(list)
TypeError: 'type' object is not iterable

======================================================================
FAIL: test_histogram (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 84, in test_histogram
    'Erreur dans les histogrammes'
AssertionError: [({}, []), ({}, [])] is not an instance of <class 'dict'> : First argument is not a dictionary

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1, errors=3)
